In [12]:
# Getting whole dataset
import os
folder_path = r"C:\Users\huyen\OneDrive - UNT System\A_PhD_PATH\Medical Concept Normalization\DATA\ORIGINAL DATASET\datasets\datasets\TwADR-L"

all_lines = []
for file in os.listdir(folder_path):
    # Check whether file is in text format or not
    if file.endswith(".txt"):
        file_path = f"{folder_path}\{file}"
        # read text file 
        file = open(file_path, "r")
        text = file.read()
        for line in text.split('\n'):
            all_lines.append(line.split('\t'))

In [14]:
df = pd.DataFrame(all_lines, columns = ['CUIs', 'concepts', 'tw_phrases'] )
df

,CUIs,concepts,tw_phrases
0,C0455769,Energy increased,still not tired
1,C0003123,Anorexia,I haven't eaten in 3 days
2,C0917801,Sleeplessness,can't remember the last time I slept
3,C0022107,Irritable Mood,I feel like
4,C0011570,Mental Depression,depression
...,...,...,...
50765,C2939186,Disturbance in mood,had me in my feelings
50766,C0042256,Vaginal itching,itching
50767,C0038587,Substance Withdrawal Syndrome,cigarette withdrawal
50768,C0152128,Drug withdrawal syndrome,tapering off prednisone
50769,,None,None

In [20]:
# Discover the concepts
## How many unique concepts?

len(df['concepts'].unique())

2221

In [23]:
# Save the unique concept
uniq_concepts = pd.DataFrame(df['concepts'].unique(), columns = ['unique_concept'])

uniq_concepts

          unique_concept
0       Energy increased
1               Anorexia
2          Sleeplessness
3         Irritable Mood
4      Mental Depression
...                  ...
2216   Uterine Neoplasms
2217           Halitosis
2218    Uterine Fibroids
2219          Dependence
2220  Uterine hemorrhage

[2221 rows x 1 columns]

In [32]:
df_mapped_uniq_concept = df[['CUIs', 'concepts']].drop_duplicates()
df_mapped_uniq_concept

          CUIs            concepts
0     C0455769    Energy increased
1     C0003123            Anorexia
2     C0917801       Sleeplessness
3     C0022107      Irritable Mood
4     C0011570   Mental Depression
...        ...                 ...
2359  C0042138   Uterine Neoplasms
2360  C0018520           Halitosis
2361  C0042133    Uterine Fibroids
2362  C0439857          Dependence
2363  C0042134  Uterine hemorrhage

[2221 rows x 2 columns]

In [33]:
with open(r'C:\Users\huyen\OneDrive - UNT System\A_PhD_PATH\Medical Concept Normalization\DATA\ORIGINAL DATASET\uniq_concepts_twADR.csv',
         'w', encoding = 'utf-8', newline = '') as f:
    df_mapped_uniq_concept.to_csv(f)

# AskPatients

In [35]:
# Getting whole dataset
import os
folder_path = r"C:\Users\huyen\OneDrive - UNT System\A_PhD_PATH\Medical Concept Normalization\DATA\ORIGINAL DATASET\datasets\datasets\AskAPatient"

all_lines = []
for file in os.listdir(folder_path):
    # Check whether file is in text format or not
    if file.endswith(".txt"):
        file_path = f"{folder_path}\{file}"
        # read text file 
        file = open(file_path, "r")
        text = file.read()
        for line in text.split('\n'):
            all_lines.append(line.split('\t'))
            
df = pd.DataFrame(all_lines, columns = ['ID', 'medical_concepts', 'phrases'] )
df

,ID,medical_concepts,phrases
0,108367008,Dislocation of joint,dislocating
1,3384011000036100,Arthrotec,Arthrotec
2,166717003,Serum creatinine raised,elevated creatine
3,3877011000036101,Lipitor,Lipitor
4,402234004,Foot eczema,Eczema on feet
...,...,...,...
173265,3877011000036101,Lipitor,lipitor
173266,248262001,Always sleepy,sleepy all or most sf the time
173267,129899009,Blood pressure alteration,slight effect on my blood pressure
173268,25064002,Headache,severe headaches
173269,,None,None

In [36]:
# Discover the concepts
## How many unique concepts?

len(df['medical_concepts'].unique())

1041

In [37]:
# Get the unique medical concepts and ID respectively
df_mapped_uniq_concept = df[['ID', 'medical_concepts']].drop_duplicates()
df_mapped_uniq_concept

                      ID         medical_concepts
0              108367008     Dislocation of joint
1       3384011000036100                Arthrotec
2              166717003  Serum creatinine raised
3       3877011000036101                  Lipitor
4              402234004              Foot eczema
...                  ...                      ...
52199          129565002       Disorder of muscle
52462           57676002               Joint pain
52472          424196004              Nervousness
104284          55300003             Muscle Cramp
139393          95847005            Muscle injury

[1043 rows x 2 columns]

In [38]:
with open(r'C:\Users\huyen\OneDrive - UNT System\A_PhD_PATH\Medical Concept Normalization\DATA\ORIGINAL DATASET\uniq_concepts_AskAPatient.csv',
         'w', encoding = 'utf-8', newline = '') as f:
    df_mapped_uniq_concept.to_csv(f)

In [39]:
df.drop_duplicates()

,ID,medical_concepts,phrases
0,108367008,Dislocation of joint,dislocating
1,3384011000036100,Arthrotec,Arthrotec
2,166717003,Serum creatinine raised,elevated creatine
3,3877011000036101,Lipitor,Lipitor
4,402234004,Foot eczema,Eczema on feet
...,...,...,...
87347,129565002,Disorder of muscle,myopathy
87391,129565002,Disorder of muscle,NECK MUSCEL PROBLEMS
104284,55300003,Muscle Cramp,mussel spasms
122050,161891005,Backache,"""back labor"" pains"
139393,95847005,Muscle injury,"permanent, irreversible muscle damage"